# Generated by Django 3.0.4 on 2020-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
        migrations.AddField(
            model_name='event',
            name='endHour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='startHour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
