# Generated by Django 3.0.4 on 2020-06-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0003_event_projectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endHour',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startHour',
            new_name='startTime',
        ),
    ]
