# Generated by Django 3.0.4 on 2020-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0004_auto_20200613_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='projectId',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
