# Generated by Django 3.0.4 on 2020-06-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0005_auto_20200613_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='projectId',
            new_name='itemId',
        ),
    ]
