# Generated by Django 3.0.4 on 2020-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0002_auto_20200608_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='projectId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
