# Generated by Django 3.0.4 on 2020-06-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0006_auto_20200613_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='itemId',
            new_name='projectTaskId',
        ),
    ]
