# Generated by Django 3.0.4 on 2020-06-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0007_auto_20200614_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='projectTaskId',
            new_name='itemId',
        ),
    ]
