# Generated by Django 3.0.4 on 2020-05-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('psychologicalManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.Account'),
        ),
    ]
