# Generated by Django 3.0.4 on 2020-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologicalManagement', '0005_remove_psychologicalmodel_last_compelte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalmodel',
            name='dateTaken',
            field=models.DateField(auto_now=True),
        ),
    ]
