# Generated by Django 3.0.4 on 2020-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologicalManagement', '0006_auto_20200507_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalmodel',
            name='dateTaken',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
