# Generated by Django 3.0.4 on 2020-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_compelte', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('formType', models.CharField(choices=[('MD', 'MADRS'), ('KD', 'KEDS')], max_length=2)),
            ],
        ),
    ]
