# Generated by Django 3.0.4 on 2020-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologicalManagement', '0002_psychologicalmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologicalmodel',
            old_name='user',
            new_name='account',
        ),
    ]
