# Generated by Django 3.0.4 on 2020-05-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologicalManagement', '0004_psychologicalmodel_datetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicalmodel',
            name='last_compelte',
        ),
    ]
